dist: bionic
language: minimal

script:
 - sudo apt-get install -y linux-modules-extra-$(uname -r)
 - sudo modprobe zram
 - free -m
 - sudo apt-get install zram-config
 - free -m
 - sudo service zram-config restart
 - sudo systemctl status zram-config.service
 - sudo /usr/bin/init-zram-swapping
 - sudo bash -x /usr/bin/init-zram-swapping
# - sudo journalctl -xe | cat
 - zramctl
 - free -m 
 - cat /proc/swaps
