dist: bionic
language: minimal

script:
 - free -m
 - sudo apt-get install -y linux-modules-extra-$(uname -r) zram-config
 - sudo zramctl
 - free -m
 - cat /proc/swaps
 - sudo /usr/bin/init-zram-swapping
 - sudo zramctl
 - free -m
 - cat /proc/swaps
 - exit 0

