dist: bionic
language: generic

script:
 - free -m
 - sudo apt-get install zram-config
 - sudo service zram-config restart
 - systemctl status zram-config.service
 - journalctl -xe | cat
 - zramctl
 - free -m 
 - cat /proc/swaps
