dist: bionic
language: generic

script:
 - free -m
 - sudo apt-get install zram-config
 - sudo service zram-config restart
 - sudo systemctl status zram-config.service
 - sudo /usr/bin/init-zram-swapping
 - sudo bash -x /usr/bin/init-zram-swapping
 - sudo journalctl -xe | cat
 - zramctl
 - free -m 
 - cat /proc/swaps
