dist: bionic
language: minimal

jobs:
  include:
    - stage: stage1
      before-script:
      - export timeout=50
      script:
      - echo $timeout
    - stage: stage2
      script:
      - echo a
script:
- echo b
